/**
 * List of topics for generating simile quiz questions
 * Each topic should be kid-friendly and engaging for 7-9 year olds
 */
export const quizTopics = [
  "Shrek",
  "Disney Princesses",
  "Superheroes",
  "Roblox",
  "Dinosaurs",
  "Ocean Life",
  "Fairy Tales",
  "Beauty and the Beast",
  "Cinderella",
  "Snow White",
  "Sleeping Beauty",
  "The Little Mermaid",
  "Aladdin",
  "Zoo Animals",
  "Frogs",
  "Soccer",
  "Ronaldo",
  "Messi",
  "Sports Stars",
  "Pirates",
  "Dragons",
  "Wizards",
  "Jungle Adventures",
  "Ice Age",
  "Toy Story",
  "The Lion King",
  "Finding Nemo",
  "TikTok Memes",
  "Celebrities",
  "Cartoons",
  "Animals",
  "Food",
  "Cars",
  "Toys",
  "Video Games",
  "Music",
  "Art",
  "Mr Beast",
  "Rebecca Zamolo"
]; 